title: Jake Hull
#logo: /assets/img/headshot_circle.png
description: Portfolio of previous work
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
show_downloads: false
